version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /tmp/circleci
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and Save to Azure ACR
          command: |
            IMAGE=$DOCKER_ID.azurecr.io/circleci/ruby-hello-world:$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_ID -p $DOCKER_PWD $DOCKER_ID.azurecr.io
            docker build -t $IMAGE ./src
            docker push $IMAGE
