version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /tmp/circleci
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and Save to Azure ACR
          command: |
            IMAGE=$DOCKER_ID.azurecr.io/circleci/ruby-hello-world:$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_ID -p $DOCKER_PWD $DOCKER_ID.azurecr.io
            docker build -t $IMAGE ./src
            docker push $IMAGE
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: /tmp/circleci
    steps:
      - run:
          name: Install Azure CLI
          command: pip install --user azure-cli
      - run:
          name: Login and Deploy to Azure Wep App
          command: |
            az login --service-principal -u $SP_ID -p $SP_PWD --tenant $SP_TENANT
            IMAGE=$DOCKER_ID.azurecr.io/circleci/ruby-hello-world:$CIRCLE_BUILD_NUM
            az webapp config container set -n amp-site-circleci -g amp-app-20181111-rg -c $IMAGE
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master